const randomstring = require('randomstring');

class Events{
    constructor(name, description = "", startDateTime, duration, isActive = true, image = "defaultImage.jpg", capacity = 1000, ticketsAvailable = capacity, categoryId){
        this.id = autogenerated();
        this.name = name;
        this.description = description;
        this.startDateTime = startDateTime;
        this.duration = duration;
        this.isActive = isActive;
        this.image = image;
        this.capacity = capacity;
        this.ticketsAvailable = ticketsAvailable;
        this.categoryId = categoryId;
    }
}

function autogenerated(){

    let auto = 'E';

    let string = randomstring.generate({
        length: 2,
        charset: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
        });

    auto += string;
    auto += '-'

    for (let i = 0; i < 4; i++){
        auto += Math.floor(Math.random() * 10);
    }
    return auto;
}

module.exports = Events;
